name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # Modified condition to handle both direct pushes and merged PRs
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate index files
        run: |
          cd public/data
          for dir in */; do
            if [ -d "$dir" ]; then
              cd "$dir"
              find . -maxdepth 1 -name "*.md" -exec basename {} \; | \
              jq -R -s -c 'split("\n")[:-1]' > index.json
              cd ..
            fi
          done

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'  # Add caching for faster installations

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci  # Use ci instead of install for cleaner, more reliable builds

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
